version: '2'

services:

  consul-server:
    container_name: consul
    image: consul
    network_mode: host
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    command: agent -server -bind=$HOST_IP -bootstrap-expect=1 -client=$HOST_IP

  registrator:
    container_name: registrator
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -ip $HOST_IP consul://$CONSUL_IP:8500

  proxy:
    container_name: docker-flow-proxy
    image: vfarcic/docker-flow-proxy
    environment:
      CONSUL_ADDRESS: $CONSUL_IP:8500
    volumes:
      - ./test_configs/:/consul_templates/
    ports:
      - 80:80
      - 443:443
      - 8080:8080

  jenkins:
    container_name: jenkins
    image: jenkins:1.651.2
    ports:
      - 8080:8080

  jenkins-agent:
    container_name: jenkins-agent
    image: jenkinsci/ssh-slave
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=${SSH_KEY}