version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: node_modules/.bin/nodemon server.js
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:3000
