
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('users').del(),

    knex('users').insert([
      {
        "id": 1,
        "name": "Christopher"
      }, {
        "id": 2,
        "name": "Marilyn"
      }, {
        "id": 3,
        "name": "Steve"
      }, {
        "id": 4,
        "name": "Lawrence"
      }, {
        "id": 5,
        "name": "Justin"
      }, {
        "id": 6,
        "name": "Sharon"
      }, {
        "id": 7,
        "name": "Joshua"
      }, {
        "id": 8,
        "name": "Anna"
      }, {
        "id": 9,
        "name": "Ruth"
      }, {
        "id": 10,
        "name": "Brenda"
      }, {
        "id": 11,
        "name": "David"
      }, {
        "id": 12,
        "name": "Harry"
      }, {
        "id": 13,
        "name": "Margaret"
      }, {
        "id": 14,
        "name": "Nicole"
      }, {
        "id": 15,
        "name": "Peter"
      }, {
        "id": 16,
        "name": "Carlos"
      }, {
        "id": 17,
        "name": "Craig"
      }, {
        "id": 18,
        "name": "Phyllis"
      }, {
        "id": 19,
        "name": "James"
      }, {
        "id": 20,
        "name": "Paul"
      }, {
        "id": 21,
        "name": "Amy"
      }, {
        "id": 22,
        "name": "Gerald"
      }, {
        "id": 23,
        "name": "Sarah"
      }, {
        "id": 24,
        "name": "Debra"
      }, {
        "id": 25,
        "name": "Annie"
      }, {
        "id": 26,
        "name": "Joshua"
      }, {
        "id": 27,
        "name": "Alice"
      }, {
        "id": 28,
        "name": "Beverly"
      }, {
        "id": 29,
        "name": "Philip"
      }, {
        "id": 30,
        "name": "Jerry"
      }, {
        "id": 31,
        "name": "Wanda"
      }, {
        "id": 32,
        "name": "Rachel"
      }, {
        "id": 33,
        "name": "Theresa"
      }, {
        "id": 34,
        "name": "Jason"
      }, {
        "id": 35,
        "name": "Norma"
      }, {
        "id": 36,
        "name": "Samuel"
      }, {
        "id": 37,
        "name": "Jason"
      }, {
        "id": 38,
        "name": "Lori"
      }, {
        "id": 39,
        "name": "Emily"
      }, {
        "id": 40,
        "name": "Mildred"
      }, {
        "id": 41,
        "name": "Marie"
      }, {
        "id": 42,
        "name": "Jeffrey"
      }, {
        "id": 43,
        "name": "Alice"
      }, {
        "id": 44,
        "name": "Douglas"
      }, {
        "id": 45,
        "name": "Patricia"
      }, {
        "id": 46,
        "name": "Gary"
      }, {
        "id": 47,
        "name": "Michael"
      }, {
        "id": 48,
        "name": "Bonnie"
      }, {
        "id": 49,
        "name": "Anne"
      }, {
        "id": 50,
        "name": "Dennis"
      }, {
        "id": 51,
        "name": "Alan"
      }, {
        "id": 52,
        "name": "Theresa"
      }, {
        "id": 53,
        "name": "Albert"
      }, {
        "id": 54,
        "name": "Justin"
      }, {
        "id": 55,
        "name": "Martha"
      }, {
        "id": 56,
        "name": "Mark"
      }, {
        "id": 57,
        "name": "Thomas"
      }, {
        "id": 58,
        "name": "Helen"
      }, {
        "id": 59,
        "name": "Jessica"
      }, {
        "id": 60,
        "name": "Marie"
      }, {
        "id": 61,
        "name": "Eugene"
      }, {
        "id": 62,
        "name": "Keith"
      }, {
        "id": 63,
        "name": "Charles"
      }, {
        "id": 64,
        "name": "Jacqueline"
      }, {
        "id": 65,
        "name": "David"
      }, {
        "id": 66,
        "name": "Richard"
      }, {
        "id": 67,
        "name": "Andrea"
      }, {
        "id": 68,
        "name": "Nicholas"
      }, {
        "id": 69,
        "name": "George"
      }, {
        "id": 70,
        "name": "Donald"
      }, {
        "id": 71,
        "name": "Aaron"
      }, {
        "id": 72,
        "name": "Kathleen"
      }, {
        "id": 73,
        "name": "Betty"
      }, {
        "id": 74,
        "name": "Kimberly"
      }, {
        "id": 75,
        "name": "Kathy"
      }, {
        "id": 76,
        "name": "Ashley"
      }, {
        "id": 77,
        "name": "Jane"
      }, {
        "id": 78,
        "name": "Andrew"
      }, {
        "id": 79,
        "name": "Steven"
      }, {
        "id": 80,
        "name": "Donna"
      }, {
        "id": 81,
        "name": "Craig"
      }, {
        "id": 82,
        "name": "Steven"
      }, {
        "id": 83,
        "name": "Richard"
      }, {
        "id": 84,
        "name": "Keith"
      }, {
        "id": 85,
        "name": "Gloria"
      }, {
        "id": 86,
        "name": "Anthony"
      }, {
        "id": 87,
        "name": "Joan"
      }, {
        "id": 88,
        "name": "Virginia"
      }, {
        "id": 89,
        "name": "Michelle"
      }, {
        "id": 90,
        "name": "Jane"
      }, {
        "id": 91,
        "name": "Kevin"
      }, {
        "id": 92,
        "name": "Andrew"
      }, {
        "id": 93,
        "name": "Jeremy"
      }, {
        "id": 94,
        "name": "Edward"
      }, {
        "id": 95,
        "name": "Harold"
      }, {
        "id": 96,
        "name": "Todd"
      }, {
        "id": 97,
        "name": "Tammy"
      }, {
        "id": 98,
        "name": "Tammy"
      }, {
        "id": 99,
        "name": "Catherine"
      }, {
        "id": 100,
        "name": "Lori"
      }
    ])
  );
};
